name: rideflow_app
publish_to: 'none'
description: منصة الليموزين والشحن الموحدة - RideFlow Limousine & Shipping Platform
version: 1.2.8+50

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^5.7.0
  socket_io_client: ^3.0.0
  geolocator: ^13.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_local_notifications: 17.1.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  app_links: ^6.4.0
  video_player: ^2.9.2
  rive: ^0.13.20
  model_viewer_plus: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../loogoo.jpeg"
  adaptive_icon_background: "#FF6B00"
  adaptive_icon_foreground: "../loogoo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/zoon_login_background.jpeg
    - assets/branding/zoon_logo.jpeg
    - assets/branding/zoon_icon.png
    - assets/models/
    - assets/rive/
